test:
	clang++ -o ../tetris -std=c++11 -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -ljson-c ../src/render.cpp ../src/sound.cpp ../src/input.cpp ../src/high_score.cpp ../src/tetromino.cpp ../src/game_logic.cpp ../src/game_view.cpp ../src/tetris.cpp ../src/main.cpp
